import os
import json
import sys
import shutil
import pathlib

def link_input(name, category, source_path, inputs_root):
    """
    Links a single input into the jail directory structure.
    Using 'ln -sfn' equivalent logic for atomic updates.
    """
    target_dir = inputs_root / category
    target_path = target_dir / name
    
    # Ensure category directory exists
    target_dir.mkdir(parents=True, exist_ok=True)
    
    # Create symlink (atomic update if possible, but standard overwrite here)
    if target_path.is_symlink() or target_path.exists():
        # Clean up existing link/file to ensure update
        if target_path.is_dir() and not target_path.is_symlink():
            shutil.rmtree(target_path)
        else:
            target_path.unlink()
            
    try:
        os.symlink(source_path, target_path)
    except OSError as e:
        print(f"Error linking {name}: {e}", file=sys.stderr)

def main():
    print("Initializing Mentci-AI Level 5 Jail Environment (Python)...")

    # 1. Load Structured Attributes from Nix
    # When __structuredAttrs = true, Nix exports the path to the JSON file in .attrs.json
    # However, in a shellHook, we might need to find it. 
    # Usually it's in the build directory or passed explicitly.
    # For mkShell with structuredAttrs, variables are exported, but the full JSON 
    # might effectively be what we passed in 'jailConfig'.
    
    # In this specific architecture, we are passing the config via a specific env var 
    # pointing to a JSON file generated by Nix, OR we can read the env vars if 
    # structuredAttrs export them. 
    
    # STRATEGY: We will rely on the `shellHook` to dump the config to a known JSON location
    # or pass it as an argument, since `mkShell` behavior with structuredAttrs can vary 
    # across Nix versions regarding direct .attrs.json availability in the shell itself.
    
    config_path = os.environ.get("JAIL_CONFIG_JSON")
    if not config_path or not os.path.exists(config_path):
        print("Error: JAIL_CONFIG_JSON not set or file missing.", file=sys.stderr)
        return

    with open(config_path, 'r') as f:
        config = json.load(f)

    # 2. Determine Purity Mode
    # Checking for typical impurities (like /usr/local or preserved prompts)
    is_impure = os.path.isdir("/usr/local") or "NIX_SHELL_PRESERVE_PROMPT" in os.environ
    mode = "IMPURE" if is_impure else "PURE"
    ro_indicator = "RW (Impure)" if is_impure else "RO (Pure)"
    
    # Exporting for shell usage (optional, mostly for display)
    os.environ["MENTCI_MODE"] = mode
    os.environ["MENTCI_RO_INDICATOR"] = ro_indicator
    
    print(f"Running in {mode} mode ({ro_indicator})")

    # 3. Jail Launcher Logic
    inputs_root = pathlib.Path(config["inputsPath"]).resolve()
    inputs_root.mkdir(parents=True, exist_ok=True)
    
    print("Launching Nix Jail...")
    print("Organizing inputs from data manifest...")

    input_manifest = config.get("inputManifest", {})
    
    for category, items in input_manifest.items():
        for name, path in items.items():
            link_input(name, category, path, inputs_root)

    print("Jail Launcher Complete.")
    print(f"Inputs available in '{inputs_root}':")
    
    # Simple tree-like listing
    for root, dirs, files in os.walk(inputs_root):
        level = root.replace(str(inputs_root), '').count(os.sep)
        indent = ' ' * 4 * (level)
        print(f"{indent}{os.path.basename(root)}/")
        subindent = ' ' * 4 * (level + 1)
        for f in files:
            print(f"{subindent}{f}")
        for d in dirs:
             # Just print dir names, recursion handles content
             pass

    # 4. Display Context
    context_file = pathlib.Path("Level5-Ai-Coding.md")
    if context_file.exists():
        print("\n--- Level 5 Programming Context ---\n")
        print(context_file.read_text())
        print("\n-----------------------------------\n")

    print("Welcome to the Mentci-AI Jail.")

if __name__ == "__main__":
    main()
