[workspace]
resolver = "2"
members = [
    "Components/AI",
    "Components/aski-lib",
    "Components/chronos",
    "Components/chronos-lib",
    "Components/criome-core",
    "Components/mentci-box",
    "Components/mentci-box-lib",
    "Components/mentci-execute",
    "Components/mentci-launch",
    "Components/mentci-mcp",
    "Components/mentci-mcp/core",
    "Components/mentci-mcp/jj",
    "Components/mentci-mcp/capnp",
    "Components/mentci-mcp/edit",
    "Components/mentci-stt",
    "Components/mentci-user",
    "Components/mentci-vcs"
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
